version: "3.7"

services:
    server:
        container_name: gql-test-server
        env_file: .env
        environment:
            DEPEND_HOST: postgres
            DEPEND_PORT: ${PG_PORT}
        volumes:
            - ./services/api/src:/usr/src/app/src:delegated
            - /usr/src/app/node_modules
        depends_on:
            - postgres
            - redis
        networks:
            - postgres
            - redis
        ports:
            - ${PORT}:${PORT}
        build:
            context: .
            dockerfile: ./docker/Dockerfile.dev
            # target: development
            # args:
            #     mode: development

    postgres:
        container_name: gql-test-postgres
        image: postgres:latest
        env_file: .env
        environment:
            POSTGRES_DATABASE: ${PG_DATABASE}
            POSTGRES_USER: ${PG_USER}
            POSTGRES_PASSWORD: ${PG_PASSWORD}
            # command: "postgres -c config_file=/usr/local/etc/postgres/postgres.conf"
        ports:
            - "${PG_PORT}:${PG_PORT}"
        volumes:
            # - "./docker/postgres.conf:/usr/local/etc/postgres/postgres.conf"
            - /var/run/postgres/postgres.sock
            - pgdata:/var/lib/postgresql/data
        networks:
            - postgres
        restart: unless-stopped
   
    redis:
        container_name: gql-test-redis
        image: redis
        command: redis-server /usr/local/etc/redis/redis.conf
        volumes:
            - redis:/usr/local/etc/redis/data
            - ./docker/configs/redis.conf:/usr/local/etc/redis/redis.conf
        networks:
            - redis
        ports:
            - ${RD_PORT}:${RD_PORT}
        expose:
            - ${RD_PORT}

    redis-commander:
        container_name: gql-test-redis-commander
        hostname: redis-commander
        image: rediscommander/redis-commander:latest
        environment:
            - REDIS_HOSTS=local:redis:${RD_PORT}
        networks:
            - redis
        ports:
            - ${RDC_PORT}:${RDC_PORT}

volumes:
    pgdata:
    redis:
    
networks:
    postgres:
        driver: bridge
    redis:
        driver: bridge