FROM node:latest

RUN apt-get clean && apt-get -y update && apt-get -y dist-upgrade
RUN npm install -g npm

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY ./package*.json ./
COPY ./.eslintrc.js ./
COPY ./tsconfig.json ./

# Package lock for npm install
COPY ./services/api/package*.json ./services/api/

# Install packages
RUN npm install

# Bundle api source
COPY ./services/api services/api

RUN cd ./services/api && npm install
RUN cd ./services/api && npm run build

# Add docker util files
COPY ./docker/utils/docker-entrypoint.sh ./
COPY ./docker/utils/wait-for-it.sh ./

# Set permissions to execute
RUN chmod +x ./wait-for-it.sh ./docker-entrypoint.sh

# Service entry port
EXPOSE 5000

# Wait for it docker entry
# ENTRYPOINT ["./docker-entrypoint.sh"]
CMD "npm" "run" "serve:dev"