FROM node:latest

# Update the Node image to keep up with potential security issues
RUN apt-get clean && apt-get -y update && apt-get -y dist-upgrade

# Create app and enter the root directory
RUN mkdir -p /app
WORKDIR /app

# Copy root files
COPY package*.json ./
COPY .eslintrc.js ./
COPY tsconfig.json ./
COPY services/client/package*.json services/client/

RUN npm install

COPY services/client services/client
WORKDIR services/client
RUN npm install

EXPOSE 3000

# Running the app
CMD ["npm", "run", "dev"]
